blank_issues_enabled: false
contact_links:
  - name: 💬 GitHub Discussions
    url: https://github.com/moonshadowrev/eXtensibleSH/discussions
    about: Ask questions, share ideas, and discuss with the community
  - name: 🔒 Security Issues
    url: https://github.com/moonshadowrev/eXtensibleSH/security/advisories
    about: Report security vulnerabilities privately
  - name: 📚 Documentation
    url: https://moonshadowrev.github.io/eXtensibleSH/
    about: Browse the complete documentation and user guides
  - name: 🔧 Usage Guide
    url: https://github.com/moonshadowrev/eXtensibleSH/blob/main/docs/usage.md
    about: Learn how to use eXtensibleSH effectively
  - name: 🔌 Plugin Development
    url: https://github.com/moonshadowrev/eXtensibleSH/blob/main/docs/how-to-create-plugin.md
    about: Learn how to create and contribute plugins
  - name: 🌟 Third-Party Scripts
    url: https://github.com/moonshadowrev/eXtensibleSH/blob/main/thirdparty/README.md
    about: Learn about third-party scripts and community contributions 